application: 920-checkin
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: js
- url: /
  static_files: index.html
  upload: index.html
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /.*
  script: main.app

builtins:
- appstats: on
